### ISSUE TITLE
Issue/Suggestion: No Config file generates

### ISSUE THREAD

**Issue by InvisibleSpiders** [DrgnFireYellow/Homeland#5]
When plugin loads, no config folder/file is generated.

Suggest adding adjustable parameters. 
World size per rank, economy features, player managed world flags, etc.

**Comment by InvisibleSpiders** [comment]
Possibly add a few options to allow/deny McMMO Exp gain, job money gain, etc in the homeland worlds.

**Comment by DrgnFireYellow** [comment]
Thanks for the suggestion! I actually already have something like this in the development build and will probably push it out later this month.

**Comment by DrgnFireYellow** [comment]
I just realized that you posted this 2 months ago. Sorry for not responding sooner.

**Comment by InvisibleSpiders** [comment]
> I just realized that you posted this 2 months ago. Sorry for not responding sooner.

No problem!

Looking forward to the coming build!

**Comment by DrgnFireYellow** [comment]
If you want to try them early, you can download them [here](https://github.com/DrgnFireYellow/Homeland/actions). Just click the one at the top and scroll down.

**Comment by InvisibleSpiders** [comment]
Will do, thanks! Next week as I'm on a road trip currently.
